[theme]
primaryColor="#0891b2"
backgroundColor="#f8f9fa"
secondaryBackgroundColor="#ffffff"
textColor="#333333"
font="sans serif"

[client]
showErrorDetails=true

[logger]
level="info"

[server]
port = 8501
headless = true
runOnSave = true
maxUploadSize = 200
